### PR TITLE
Create Quick_sort.cpp

### PR DESCRIPTION
**Pull request by Bikash0007**
Quicksort in CPP

### CODE REVIEW

**Comment by Bikash0007** [comment]
Can you please add the label hacktoberfest accepted?

**Comment by ShivamYadav-Coding** [comment]
This repository have hacktoberfest topic so every pull request should be accepted by hacktoberfest with the requirement of adding hacktoberfest-accepted label.
Are you facing any problems?

**Comment by Bikash0007** [comment]
I had participated for the first time since I have less experience some of my elders who had already participated in hacktoberfest previously are saying to ask my owner why there has been no hacktoberfest label inserted as your pull request has been closed by your owner.

**Comment by ShivamYadav-Coding** [comment]
But did you find any issue when you logged on to hacktoberfest website?

**Comment by Bikash0007** [comment]
No! It's alright.

**Comment by Bikash0007** [comment]
Thank you for inserting the label!

**Comment by Bikash0007** [comment]
Hello! Why my projects had been excluded from hactoberfest?

**Comment by ShivamYadav-Coding** [comment]
@Bikash0007 please refer here #140

**Comment by Bikash0007** [comment]
So can I apply now  for other pull requests.

**Comment by ShivamYadav-Coding** [comment]
You should not contribute to this repository. If your goal is to complete 4 pull request for Hacktoberfest. Since Hacktoberfest will not count pull request made to this repository.

**Comment by Bikash0007** [comment]
Ok but I can go for other repositories.

**Comment by ShivamYadav-Coding** [comment]
yes

**Pull request merged**
